### ISSUE TITLE
Write Script to Dynamically Set Terraform S3 Backend Key

### ISSUE THREAD

**Issue by dav3r** [cisagov/cool-accounts#34]
The script should edit `cool-accounts/dynamic/backend.tf` and replace `DYNAMIC_ACCOUNT_NAME` with an input parameter (e.g. `env0`).

For bonus points, the script could also have a switch to optionally output an initial `env0.tfvars` file.

**Comment by felddy** [comment]
This looks relevant: 
https://www.terraform.io/docs/configuration/functions/templatefile.html
